<a href="https://colab.research.google.com/github/alvin870203/ntuml21s/blob/main/Copy_of_Pytorch_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pytorch Tutorial**


In [ ]:
import torch

**1. Pytorch Documentation Explanation with torch.max**



In [ ]:
x = torch.randn(4,5)
y = torch.randn(4,5)
z = torch.randn(4,5)
print(x)
print(y)
print(z)

tensor([[-1.4692,  0.1589, -0.6856, -0.2181,  1.3996],
        [-0.0425, -0.9969,  0.6644,  0.8460,  0.8456],
        [ 0.6248,  0.8077, -2.4870, -1.4152,  1.9540],
        [-0.7800,  1.8289,  0.8991,  1.6792, -0.1541]])
tensor([[-0.6047, -1.2365,  1.0895, -0.1864, -1.0349],
        [ 0.9820, -0.0843,  0.9576, -1.0421, -3.0865],
        [ 0.2383, -0.6807, -1.6543, -1.8849,  0.6176],
        [ 0.5364, -0.0263,  1.3691,  0.3651,  0.3730]])
tensor([[-1.0275, -1.5200,  0.2030, -1.4512,  0.2611],
        [ 0.8778,  0.1176, -0.8036,  0.3292,  2.5972],
        [ 0.6502,  0.5989,  0.0831, -0.8097, -0.4106],
        [-0.3020,  1.3174,  0.5711, -0.9270, -1.8464]])


In [ ]:
# 1. max of entire tensor (torch.max(input) → Tensor)
m = torch.max(x)
print(m)

tensor(1.9540)


In [ ]:
# 2. max along a dimension (torch.max(input, dim, keepdim=False, *, out=None) → (Tensor, LongTensor))
m, idx = torch.max(x,0)
print(m)
print(idx)

tensor([0.6248, 1.8289, 0.8991, 1.6792, 1.9540])
tensor([2, 3, 3, 3, 2])


In [ ]:
# 2-2
m, idx = torch.max(input=x,dim=0)
print(m)
print(idx)

tensor([0.6248, 1.8289, 0.8991, 1.6792, 1.9540])
tensor([2, 3, 3, 3, 2])


In [ ]:
# 2-3
m, idx = torch.max(x,0,False)
print(m)
print(idx)

tensor([0.6248, 1.8289, 0.8991, 1.6792, 1.9540])
tensor([2, 3, 3, 3, 2])


In [ ]:
# 2-4
m, idx = torch.max(x,dim=0,keepdim=True)
print(m)
print(idx)

tensor([[0.6248, 1.8289, 0.8991, 1.6792, 1.9540]])
tensor([[2, 3, 3, 3, 2]])


In [ ]:
# 2-5
p = (m,idx)
torch.max(x,0,False,out=p)
print(p[0])
print(p[1])


tensor([0.6248, 1.8289, 0.8991, 1.6792, 1.9540])
tensor([2, 3, 3, 3, 2])


In [ ]:
# 2-6
p = (m,idx)
torch.max(x,0,False,p)
print(p[0])
print(p[1])
# *out is a keyword argument

TypeError: ignored

In [ ]:
# 2-7
m, idx = torch.max(x,True)
# *did not spcify dim

TypeError: ignored

In [ ]:
# 3. max(choose max) operators on two tensors (torch.max(input, other, *, out=None) → Tensor)
t = torch.max(x,y)
print(t)

tensor([[-0.6047,  0.1589,  1.0895, -0.1864,  1.3996],
        [ 0.9820, -0.0843,  0.9576,  0.8460,  0.8456],
        [ 0.6248,  0.8077, -1.6543, -1.4152,  1.9540],
        [ 0.5364,  1.8289,  1.3691,  1.6792,  0.3730]])


**2. Common errors**



The following code blocks show some common errors while using the torch library. First, execute the code with error, and then execute the next code block to fix the error. You need to change the runtime to GPU.


In [ ]:
import torch

In [ ]:
# 1. different device error
model = torch.nn.Linear(5,1).to("cuda:0")
x = torch.Tensor([1,2,3,4,5]).to("cpu")
y = model(x)
# *Tensor for * is on CPU, but expected them to be on GPU

RuntimeError: ignored

In [ ]:
# 1. different device error (fixed)
x = torch.Tensor([1,2,3,4,5]).to("cuda:0")
y = model(x)
print(y.shape)
# => send the tensor to GPU

torch.Size([1])


In [ ]:
# 2. mismatched dimensions error
x = torch.randn(4,5)
y= torch.randn(5,4)
z = x + y
# The size of tensor a (5) must match the size of tensor b (4) at non-singleton dimension 1

RuntimeError: ignored

In [ ]:
# 2. mismatched dimensions error (fixed)
y= y.transpose(0,1)
z = x + y
print(z.shape)
# => the shape of a tensor is incorrect, use transpose, squeeze, unsqueeze to align the dimensions

torch.Size([4, 5])


In [ ]:
# 3. cuda out of memory error
import torch
import torchvision.models as models
resnet18 = models.resnet18().to("cuda:0") # Neural Networks for Image Recognition
data = torch.randn(2048,3,244,244) # Create fake data (2048 images)
out = resnet18(data.to("cuda:0")) # Use Data as Input and Feed to Model
print(out.shape)
# CUDA out of memory. Tried to allocate 7.27 GiB (GPU 0; 14.76 GiB total capacity; 12.28 GiB already allocated; 1.42 GiB free; 12.30 GiB reserved in total by PyTorch)

RuntimeError: ignored

In [ ]:
# 3. cuda out of memory error (fixed)
for d in data:
  out = resnet18(d.to("cuda:0").unsqueeze(0))
print(out.shape)
# => The batch size of data is too large to fit in the GPU. Reduce the batch size
# If the data is iterated (batch size = 1), the problem will be solved. You can also use DataLoader

torch.Size([1, 1000])


In [ ]:
# 4. mismatched tensor type
import torch.nn as nn
L = nn.CrossEntropyLoss()
outs = torch.randn(5,5)
labels = torch.Tensor([1,2,3,4,0])
lossval = L(outs,labels) # Calculate CrossEntropyLoss between outs and labels
# expected scalar type Long but found Float

RuntimeError: ignored

In [ ]:
# 4. mismatched tensor type (fixed)
labels = labels.long()
lossval = L(outs,labels)
print(lossval)
# => labels must be long tensors, cast it to type "Long" to fix this issue

tensor(2.8834)


**3. More on dataset and dataloader**


A dataset is a cluster of data in a organized way. A dataloader is a loader which can iterate through the data set.

Let a dataset be the English alphabets "abcdefghijklmnopqrstuvwxyz"

In [ ]:
dataset = "abcdefghijklmnopqrstuvwxyz"

A simple dataloader could be implemented with the python code "for"

In [ ]:
for datapoint in dataset:
  print(datapoint)

When using the dataloader, we often like to shuffle the data. This is where torch.utils.data.DataLoader comes in handy. If each data is an index (0,1,2...) from the view of torch.utils.data.DataLoader, shuffling can simply be done by shuffling an index array. 



torch.utils.data.DataLoader will need two imformation to fulfill its role. First, it needs to know the length of the data. Second, once torch.utils.data.DataLoader outputs the index of the shuffling results, the dataset needs to return the corresponding data.

Therefore, torch.utils.data.Dataset provides the imformation by two functions, `__len__()` and `__getitem__()` to support torch.utils.data.Dataloader

In [ ]:
import torch
import torch.utils.data 
class ExampleDataset(torch.utils.data.Dataset):
  def __init__(self):
    self.data = "abcdefghijklmnopqrstuvwxyz"
  
  def __getitem__(self,idx): # if the index is idx, what will be the data?
    return self.data[idx]
  
  def __len__(self): # What is the length of the dataset
    return len(self.data)

dataset1 = ExampleDataset() # create the dataset
dataloader = torch.utils.data.DataLoader(dataset = dataset1,shuffle = True,batch_size = 1)
for datapoint in dataloader:
  print(datapoint)

A simple data augmentation technique can be done by changing the code in `__len__()` and `__getitem__()`. Suppose we want to double the length of the dataset by adding in the uppercase letters, using only the lowercase dataset, you can change the dataset to the following.

In [ ]:
import torch.utils.data 
class ExampleDataset(torch.utils.data.Dataset):
  def __init__(self):
    self.data = "abcdefghijklmnopqrstuvwxyz"
  
  def __getitem__(self,idx): # if the index is idx, what will be the data?
    if idx >= len(self.data): # if the index >= 26, return upper case letter
      return self.data[idx%26].upper()
    else: # if the index < 26, return lower case, return lower case letter
      return self.data[idx]
  
  def __len__(self): # What is the length of the dataset
    return 2 * len(self.data) # The length is now twice as large

dataset1 = ExampleDataset() # create the dataset
dataloader = torch.utils.data.DataLoader(dataset = dataset1,shuffle = True,batch_size = 1)
for datapoint in dataloader:
  print(datapoint)